name: Compilar Android (APK e AAB)

# Define quando esta ação será executada
on:
  push:
    branches:
      - main # Executa sempre que enviar código para a branch main
  workflow_dispatch: # Permite que dispare a compilação manualmente no GitHub

jobs:
  build-android:
    name: Compilar Aplicação Android
    runs-on: ubuntu-latest # Utiliza um servidor Linux rápido do GitHub

    steps:
      - name: 1. Obter o código do repositório
        uses: actions/checkout@v4

      - name: 2. Configurar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Versão recomendada para as versões recentes do Angular

      - name: 3. Instalar dependências (npm)
        run: npm install

      - name: 4. Compilar o projeto web (Angular)
        run: npm run build

      - name: 5. Configurar o Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21' # Padrão exigido pelo Android moderno

      - name: 6. Sincronizar o código web com o Android via Capacitor
        run: npx cap sync android

      - name: 7. Dar permissões de execução ao Gradle
        run: chmod +x android/gradlew

      - name: 8. Compilar o APK (Para testar no seu telefone)
        run: |
          cd android
          ./gradlew assembleDebug

      - name: 9. Decodificar Keystore e Compilar AAB Assinado
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: |
          # Transforma o texto de volta num ficheiro no servidor do GitHub
          echo $KEYSTORE_BASE64 | base64 --decode > $RUNNER_TEMP/keystore.jks
          
          # Entra na pasta e compila injetando a assinatura
          cd android
          ./gradlew bundleRelease \
            -Pandroid.injected.signing.store.file=$RUNNER_TEMP/keystore.jks \
            -Pandroid.injected.signing.store.password=$STORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$KEY_PASSWORD

      - name: 10. Disponibilizar o APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: PrecoFacil-APK-Teste
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: 11. Disponibilizar o AAB para Download
        uses: actions/upload-artifact@v4
        with:
          name: PrecoFacil-AAB-Producao
          path: android/app/build/outputs/bundle/release/app-release.aab